<div style="text-align: center"><img src="https://telematica.usm.cl/wp-content/themes/telematica-web/assets/img/header-usm.png" height="75"></div>

# Tarea 2 Módulos 1 y 2: Cifrado Simétrico
### Asignatura: Criptografía y Seguridad de la Información - TEL252 - 2026
#### _Docente y Autor : Berioska Contreras Vargas - berioska.contreras@usm.cl

* **Polinomios:** Pueden ser representados como una lista de coeficientes. Mediante las bibliotecas de Numpy podemos crear y modificar polinomios utilizando la clase Polynomials.  

| Referencia |
| :--- |
| [Polynomials in NumPy](https://numpy.org/doc/stable/reference/routines.polynomials.html) |

In [6]:
import numpy as np  
import numpy.polynomial as gf  
grado = 3
gf.Polynomial.basis(grado)

Polynomial([0., 0., 0., 1.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')

* **Coeficientes:** Un polinomio es tratado como una serie de potencias finitas. Por lo tanto, la serie es representada en un arreglo unidimensional basado en los coeficientes del polinomio. Cada serie es ordenada ascendentemente o de menor a mayor.

In [7]:
import numpy as np  
from numpy.polynomial import Polynomial as gf 
cf = [0,0,1]
Ax = gf.degree(cf)
mypoly = gf(cf)
print(type(mypoly))
print(mypoly.coef, mypoly.domain, mypoly.window)
print ('grado:', Ax)

z = gf.basis(deg=Ax, domain=[0,1], window=[0,1]) #
print(type(z))
print(z.coef, z.domain, z.window)

<class 'numpy.polynomial.polynomial.Polynomial'>
[0. 0. 1.] [-1.  1.] [-1.  1.]
grado: 2
<class 'numpy.polynomial.polynomial.Polynomial'>
[0. 0. 1.] [0. 1.] [0. 1.]


* **Adición:** Un polinomio permite representar un conjunto finito de enteros aceptando operaciones finitas.

In [8]:
import numpy as np  
from numpy.polynomial import Polynomial as gf 
ca = [1,1,1]
cb = [1,1,0,1]
pa = gf(ca)
pb = gf(cb)
pa + pb

Polynomial([2., 2., 1., 1.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')

* **Multiplicación:** Un campo $GF(x)$ es un conjunto finito de números que permite distintas operacionesa aritméticas.

In [9]:
import numpy as np  
from numpy.polynomial import Polynomial as gf 
ca = [1,1,1]
cb = np.flip([1,0,1])
pa = gf(ca)
pb = gf(cb)
pa * pb

Polynomial([1., 1., 2., 1., 1.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')

* **Aritmética Modular:** Las operaciones suma, resta y multiplicación se realizan en conjuntos, y todas las condiciones en $GF(x)$ son satisfechas para la adición y multiplicación como expresión modular.

In [10]:
import numpy as np
from numpy.polynomial import Polynomial as gf 
def mymod(a,b):
    return ((a + b) % 2)
ff0 = [0,0,0]
ff1 = [1,1,1]
ff2 = [1,1,1]
a, b = gf(ff0, domain=[0,1]), gf(ff1,domain=[0,1])
c = gf(ff2, domain=[0,1])
vfunc = np.vectorize(mymod)
print((a + b), '==', vfunc(ff0,ff1))
print((b + c), '<>', vfunc(ff1,ff2))
print((a + c), '<>', vfunc(ff0,ff2))

1.0 + 1.0 (-1.0 + 2.0x) + 1.0 (-1.0 + 2.0x)**2 == [1 1 1]
2.0 + 2.0 (-1.0 + 2.0x) + 2.0 (-1.0 + 2.0x)**2 <> [0 0 0]
1.0 + 1.0 (-1.0 + 2.0x) + 1.0 (-1.0 + 2.0x)**2 <> [1 1 1]


* **Multiplicación en Campos Extendidos:** Para cada número primo $p$ y entero positivo $n$, existe un $GF(x)$ de orden $p^n$, y su grupo multiplicativo es cíclico de orden $p^{(n-1)}$. Luego, necesitamos reducir polinomio para el orden dado.

In [11]:
import numpy as np
from numpy.polynomial import Polynomial as gf
x= gf([0,0,0], domain=[0,1], window=[0,1])
Ax= gf([1,1,1], domain=[0,1], window=[0,1])
Bx= gf([1,0,1], domain=[0,1], window=[0,1])
Cx= gf._get_coefficients(x,(Ax*Bx)) % 2 # Producto
print(gf(Cx))
Zx= gf.cutdeg(gf(Cx, domain=[0,1], window=[0,1]), deg=3) #Divisor
print(gf(Zx))
Qx= gf._get_coefficients(x,(Cx//Zx)) % 2 # Cociente
print(gf(Qx))

1.0 + 1.0 x + 0.0 x**2 + 1.0 x**3 + 1.0 x**4
1.0 + 1.0 x + 0.0 x**2 + 1.0 x**3
1.0 + 1.0 x


* **Inverso Multiplicativo:** Si $mcd(a,b) = 1$, los enteros $a$ y $b$ son coprimos. Este mismo principio aritmético se utiliza para los polinomios.

In [12]:
import numpy as np
from numpy.polynomial import Polynomial as gf
x= gf([0,0,0,0,0], domain=[0,1], window=[0,1])
# x^2 
Q= gf([0,0,1,0,0], domain=[0,1], window=[0,1]) 
# x^3 + x^2 + 1
cQ= gf([1,0,1,1,0], domain=[0,1], window=[0,1]) 
# x^4+x+1
R= gf([1,1,0,0,1], domain=[0,1], window=[0,1]) 
# x + 1
cR= gf([1,1,0,0,0], domain=[0,1], window=[0,1])
iQ = gf._get_coefficients(x,(cQ*Q)) % 2 
iR = gf._get_coefficients(x,(cR*R)) % 2 
print((iQ + iR) % 2)
iRQ = gf._get_coefficients(x,(iQ+iR)) % 2 
gf(iRQ)


[1. 0. 0. 0. 0. 0.]


Polynomial([1., 0., 0., 0., 0., 0.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')

### **Actividad 1**: Dado el orden $GF(2^3)$ y el polinomio $x^3 + x +1$, construya de manera programática la tabla multiplicativa adjunta. Considere que, para todo valor de $i, j \in \{1, 2, 3, 4, 5, 6, 7\}$ correspondientes a los índices de la matriz $m$, se cumple, por ejemplo, la siguiente operación:  
\begin{equation*}
m[4][3] = 4 \cdot 3 = \{100\} \cdot \{011\} = x^2 \cdot (x + 1) = x^3 + x^2 = (x + 1) + x^2 = x^2 + x + 1 = \{111\} = 7
\end{equation*}

In [19]:
import numpy as np
m = np.matrix([[1, 2, 3, 4, 5, 6, 7],
               [2, 4, 6, 3, 1, 7, 5],
               [3, 6, 5, 7, 4, 1, 2],
               [4, 3, 7, 6, 2, 5, 1],
               [5, 1, 4, 2, 7, 3, 6],
               [6, 7, 1, 5, 3, 2, 4],
               [7, 5, 2, 1, 6, 4, 3],])
    

def multiplicar(a, b):
    resultado = 0
    while b > 0:
        if b & 1:
            resultado = resultado ^ a

        b = b >> 1
        a = a << 1

        if a & 0b1000:
            a = a ^ 0b1011

    return resultado


def construir_tabla():
    m = np.zeros((7, 7), dtype=int)
    for i in range(7):
        for j in range(7):
            m[i][j] = multiplicar(i + 1, j + 1)
    return m


def formato_polinomio(valor):
    c0 = (valor >> 0) & 1
    c1 = (valor >> 1) & 1
    c2 = (valor >> 2) & 1
    
    return str(gf([c0, c1, c2]))


m = construir_tabla()

print("Tabla multiplicativa de GF(2^3):")
print(m)

print("todas las posibles multiplicaciones:\n")

for i in range(7):
    for j in range(7):

        producto = m[i][j]        
        poly_i = formato_polinomio(i + 1)
        poly_j = formato_polinomio(j + 1)
        poly_prod = formato_polinomio(producto)
        
        print(f"{poly_prod}")

Tabla multiplicativa de GF(2^3):
[[1 2 3 4 5 6 7]
 [2 4 6 3 1 7 5]
 [3 6 5 7 4 1 2]
 [4 3 7 6 2 5 1]
 [5 1 4 2 7 3 6]
 [6 7 1 5 3 2 4]
 [7 5 2 1 6 4 3]]
todas las posibles multiplicaciones:

1.0 + 0.0 x + 0.0 x**2
0.0 + 1.0 x + 0.0 x**2
1.0 + 1.0 x + 0.0 x**2
0.0 + 0.0 x + 1.0 x**2
1.0 + 0.0 x + 1.0 x**2
0.0 + 1.0 x + 1.0 x**2
1.0 + 1.0 x + 1.0 x**2
0.0 + 1.0 x + 0.0 x**2
0.0 + 0.0 x + 1.0 x**2
0.0 + 1.0 x + 1.0 x**2
1.0 + 1.0 x + 0.0 x**2
1.0 + 0.0 x + 0.0 x**2
1.0 + 1.0 x + 1.0 x**2
1.0 + 0.0 x + 1.0 x**2
1.0 + 1.0 x + 0.0 x**2
0.0 + 1.0 x + 1.0 x**2
1.0 + 0.0 x + 1.0 x**2
1.0 + 1.0 x + 1.0 x**2
0.0 + 0.0 x + 1.0 x**2
1.0 + 0.0 x + 0.0 x**2
0.0 + 1.0 x + 0.0 x**2
0.0 + 0.0 x + 1.0 x**2
1.0 + 1.0 x + 0.0 x**2
1.0 + 1.0 x + 1.0 x**2
0.0 + 1.0 x + 1.0 x**2
0.0 + 1.0 x + 0.0 x**2
1.0 + 0.0 x + 1.0 x**2
1.0 + 0.0 x + 0.0 x**2
1.0 + 0.0 x + 1.0 x**2
1.0 + 0.0 x + 0.0 x**2
0.0 + 0.0 x + 1.0 x**2
0.0 + 1.0 x + 0.0 x**2
1.0 + 1.0 x + 1.0 x**2
1.0 + 1.0 x + 0.0 x**2
0.0 + 1.0 x + 1.0 x**2
0.0 

### **Actividad 2**: Sabemos que el modo de operación del algoritmo ECB (Electronic CodeBook) es determinista.  El propósito es dividir un mensaje en bloques y cada bloque es cifrado separadamente. Analice el siguiente código que utiliza el módulo pycryptodome. Posteriormente, descargue el archivo publicado en (*) y demuestre si aquel texto plano contiene datos cifrados por ECB. Proponga una solución programática que identifique aquellos bloques.
 
| Reference |
| :--- |
| [CryptoPals Source](https://cryptopals.com/sets/1/challenges/8) |
| [Python PyCryptodome](https://pypi.org/project/pycryptodome/) |

<div style="text-align: center"><img src="https://samsclass.info/141/proj/tux.bmp" height="70" width="60"></div>

In [14]:
!pip -q install pycryptodome


[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [15]:
import io
import struct
import matplotlib.pyplot as plt
from PIL import Image
from Crypto.Cipher import AES

with open("./tux.bmp", "rb") as f:
    raw = f.read()

pixel_offset = struct.unpack("<I", raw[10:14])[0]
header = raw[:pixel_offset]
pixel_data = raw[pixel_offset:]


key = bytes(16)

cipher_gcm = AES.new(key, AES.MODE_GCM)
ciphertext_gcm = cipher_gcm.encrypt(pixel_data)
bmp_gcm_bytes = header + ciphertext_gcm

pad_len = (16 - (len(pixel_data) % 16)) % 16
padded_pixels = pixel_data + b"\x00" * pad_len

cipher_ecb = AES.new(key, AES.MODE_ECB)
ciphertext_ecb = cipher_ecb.encrypt(padded_pixels)[:len(pixel_data)]
bmp_ecb_bytes = header + ciphertext_ecb

img_orig = Image.open(io.BytesIO(raw))
img_ecb  = Image.open(io.BytesIO(bmp_ecb_bytes))
img_gcm  = Image.open(io.BytesIO(bmp_gcm_bytes))

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

axes[0].imshow(img_orig)
axes[0].set_title("Original (Plaintext)")
axes[0].axis("off")

axes[1].imshow(img_ecb)
axes[1].set_title("AES-ECB (Pattern Leakage)")
axes[1].axis("off")

axes[2].imshow(img_gcm)
axes[2].set_title("AES-GCM (Pseudorandom Noise)")
axes[2].axis("off")

plt.tight_layout()
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: './tux.bmp'

* **Bits y Bytes:** Desde la distribución de Python v3 es posible utilizar el tipo de dato bytes(). Este tipo de datos representa un secuencia de valores en el rango desde 0 hasta 255 (8 bits) que son almacenados de manera inalterable. 

In [ ]:
#bits
mybyte1 = int('11001000',2)
mybyte2 = int('00001000',2)
print(mybyte2 ^ mybyte1)  # a XOR b
print(mybyte2 or mybyte1) # a OR b
print(mybyte2 and mybyte1)  # a AND b
#bytes
mybyte3 = bytes(4) #inmutable  -> help(bytes)
print(mybyte3)
myarray = [mybyte3[i] for i in mybyte3]
print (myarray)    
print (type(myarray))

* **ByteArray:** Complementariamente a bytes() está el tipo de datos bytearray() que sí crea un objeto alterable. La representación de los datos puede cambiar de acuerdo al sistema. Por ejemplo, el orden de los bytes cambia según el formato Endian, los valores más grandes primero (big endian), si no los pequeños primero (little endian). Otro ejemplo, sabemos que un byte no necesita ser firmado (unsigned) para representar datos en el rango positivo entre 0 y 255. Sin embargo, si fuese necesario representar valores en el rango -128 hasta +127, los bytes deben ser firmados (signed) para soportar un recorrido negativo. Ref.: https://docs.python.org/3/library/stdtypes.html

In [ ]:
#bloques
mybytestream = [255,255,255,255] 
myblock = bytearray(mybytestream)
print(myblock[:2],'y',myblock[-2:])
print(bytearray(str(myblock),'utf-8'))

#formato
k = bytes([128,192,240,255])
print(k[1:2] , '=', bytes(k[1:2]))
ki = int.from_bytes(k[1:2], byteorder='big', signed=False)
kj = int.from_bytes(k[1:2], byteorder='little', signed=True)
print(ki, '!=', kj)

bytearray(b'\xff\xff') y bytearray(b'\xff\xff')
bytearray(b"bytearray(b\'\\xff\\xff\\xff\\xff\')")
b'\xc0' = b'\xc0'
192 != -64


* **Cifrado de Bloques:** Sabemos que AES opera en bytes y que utiliza múltiples tamaños de llave, así como un número variable de ciclos e incluso soporta múltiples bloques desde 128bits hasta 256bits. Sin embargo, qué sucede cuando el bloque tiende a ser pequeño? analice los eventuales riesgos del siguiente ejemplo.

In [ ]:
import numpy as np
import string
def funcionF(a,b):
    K = np.array([1,1,0,0,1,1,0,0])
    X = ((a + b) % 2) ^ K   
    return X 
def funcionR(a,b):
    A_str = ''.join(str(x) for x in a)
    B_str = ''.join(str(x) for x in b)
    return (int(A_str,2),int(B_str,2))
M = '1111000011111111'
bloques = [M[i:i+8] for i in range(0,len(M),8)]
bloqueA = np.array(list(f'{int(bloques[0],2):b}'), dtype=int)
bloqueB = np.array(list(f'{int(bloques[1],2):b}'), dtype=int)
print(bloqueA, 'y', bloqueB)
print(funcionR(bloqueA,bloqueB))
A, B = (bloqueA ^ funcionF(bloqueA,bloqueB)), (bloqueB ^ funcionF(bloqueA,bloqueB))
print(funcionR(A,B))
C1, C2 = (A ^ funcionF(A,B)), (B ^ funcionF(A,B))
print(funcionR(C1,C2))

[1 1 1 1 0 0 0 0] y [1 1 1 1 1 1 1 1]
(240, 255)
(51, 60)
(240, 255)


* **Doble Cifrado:** Si la debilidad del algoritmo DES recae en la longitud de llave, entonces un doble cifrado qué más seguro podría ser? analice el siguiente código.

In [ ]:
def funcionW(m):
    B = [bin(M[i]) for i in range(len(M))]
    T = [B[i][2:] for i in range(len(B))]
    return T
def funcionQ(k):
    S = [bin(k[n]) for n in range(len(k))]
    V = [S[n][2:] for n in range(len(S))]
    return V
def funcionE(x,y,z):
    return ((x ^ y)^z)
K0 = bytes([254,255,254,255])  
K1 = bytes([254,255,254,255])  
M = bytes([128,192,240,255])

MX = np.zeros((4,8),dtype=int)
KX0, KX1 = np.zeros((4,8),dtype=int), np.zeros((4,8),dtype=int)
for i in range(0,4):
    for j in range (0,8):         
        t0 = funcionW(M)[i][j:j+1]
        t1, t2 = funcionQ(K0)[i][j:j+1], funcionQ(K1)[i][j:j+1]
        MX[i][j] = t0
        KX0[i][j], KX1[i][j] = t1, t2

print(funcionE(MX,KX0,KX1))

[[1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 1 1]]


* **Perfilamiento del Tiempo:** Así como el efecto avalancha intenta estimar el porcentaje de difusión de los bits permutados. El perfilamiento del tiempo intenta medir la eficiencia o el tiempo que tarda la ejecución de alguna rutina, ya sea una línea o un módulo.

| Referencia |
| :--- |
| [Python Profilers](https://docs.python.org/3.15/library/profiling.html)|
| [Python Execution Time](https://docs.python.org/3.15/library/timeit.html)|

In [ ]:
import timeit
import numpy as np

p = [2, 3, 7, 11, 13]
r = [2, 4, 6, 8, 10]
large_a, large_b = [1, 2] * 10**5, [2, 3] * 10**5

a_np = np.array(p)
large_a_np = np.array(large_a)
large_b_np = np.array(large_b)

%timeit -r 5 -n 1000 [x * 5 for x in p]
%timeit -r 5 -n 1000 a_np * 5

%timeit -r 3 -n 5 [sum(x) for x in zip(large_a, large_b)]
%timeit -r 7 -n 50 large_a_np + large_b_np

setup_code = """
import numpy as np
large_a, large_b = [1, 2] * 10**5, [2, 3] * 10**5
large_a_np = np.array(large_a)
large_b_np = np.array(large_b)
"""

py_zip_time = timeit.timeit(
    stmt="[sum(x) for x in zip(large_a, large_b)]",
    setup=setup_code,
    number=10
)

np_add_time = timeit.timeit(
    stmt="large_a_np + large_b_np",
    setup=setup_code,
    number=10
)

print(f"Pure Python (zip + sum): {py_zip_time / 10:.5f} s per loop")
print(f"NumPy SIMD Vectorized:   {np_add_time / 10:.5f} s per loop")
print(f"Speedup Factor:          {py_zip_time / np_add_time:.1f}x")

254 ns ± 7.58 ns per loop (mean ± std. dev. of 5 runs, 1,000 loops each)
1.34 μs ± 242 ns per loop (mean ± std. dev. of 5 runs, 1,000 loops each)
35.5 ms ± 6.93 ms per loop (mean ± std. dev. of 3 runs, 5 loops each)
809 μs ± 75.7 μs per loop (mean ± std. dev. of 7 runs, 50 loops each)
Pure Python (zip + sum): 0.02435 s per loop
NumPy SIMD Vectorized:   0.00064 s per loop
Speedup Factor:          37.8x


In [ ]:
import cProfile
import pstats
import io

def benchmark_pure_python(a, b):
    return [sum(pair) for pair in zip(a, b)]

def benchmark_numpy(a_np, b_np):
    return a_np + b_np

pr = cProfile.Profile()
pr.enable()
result_py = benchmark_pure_python(large_a, large_b)
pr.disable()

s = io.StringIO()
ps = pstats.Stats(pr, stream=s).sort_stats(pstats.SortKey.CUMULATIVE)
ps.print_stats(10)
print(s.getvalue())

         200230 function calls (200228 primitive calls) in 0.182 seconds

   Ordered by: cumulative time
   List reduced from 82 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    0.015    0.008    0.162    0.081 C:\Users\berio\AppData\Roaming\Python\Python314\site-packages\IPython\core\interactiveshell.py:3739(run_code)
        2    0.000    0.000    0.147    0.073 {built-in method builtins.exec}
        1    0.000    0.000    0.146    0.146 C:\Users\berio\AppData\Local\Temp\ipykernel_6096\3868577766.py:1(<module>)
        1    0.081    0.081    0.146    0.146 C:\Users\berio\AppData\Local\Temp\ipykernel_6096\3868577766.py:5(benchmark_pure_python)
   200000    0.076    0.000    0.076    0.000 {built-in method builtins.sum}
        2    0.008    0.004    0.015    0.008 {method '__exit__' of 'sqlite3.Connection' objects}
        2    0.000    0.000    0.000    0.000 C:\Users\berio\AppData\Roaming\Python\Python314\site-packa

* **Padding:** En los modos de cifrado por bloques se necesita que el mensaje en texto plano tenga un valor múltiplo con respecto al tamaño del bloque, y de no ser así debemos completar el bloque para satisfacer la operación.

In [ ]:
v = np.arange(1,9,1)
mv = v.reshape((2,4))
print(mv)
np.pad(mv,(0,4),'constant', constant_values=(0))

k = bytes([254,255]) 
mk = np.array(bytearray(k),dtype=int)
print(mk)
np.pad(mk,(0,4),'constant', constant_values=(0))
#np.pad()

[[1 2 3 4]
 [5 6 7 8]]
[254 255]


array([254, 255,   0,   0,   0,   0])

### **Actividad 3**: En AES, los bytes se tratan como elementos del Galois Field $GF(2^8)$ módulo el polinomio irreducible:

$$P(x) = x^8 + x^4 + x^3 + x + 1 \quad (\texttt{0x11B})$$

El paso no lineal del S-Box de AES se basa en calcular el inverso multiplicativo (multiplicative inverse) $a^{-1} \in GF(2^8)$ tal que $a \cdot a^{-1} \equiv 1 \pmod{P(x)}$.

implementa xtime(b) para multiplicar un byte por $x \pmod{P(x)}$ utilizando únicamente bit-shifts y operaciones XOR:

In [ ]:
def xtime(b: int) -> int:
    return ((b << 1) ^ 0x1B) & 0xFF if (b & 0x80) else (b << 1) & 0xFF

Utiliza xtime para construir un multiplicador general gmult(a, b) para todo par de bytes $a, b \in GF(2^8)$.

Por el Pequeño Teorema de Fermat en campos finitos (finite fields), para cualquier elemento no nulo $\alpha \in GF(2^8)$:

$$\alpha^{2^8 - 1} = \alpha^{255} = 1 \implies \alpha^{-1} = \alpha^{254}$$

Implementa gf_inv(a) utilizando ya sea el Extended Euclidean Algorithm para polinomios o exponenciación binaria (square-and-multiply) para computar $a^{254}$.

Verifica que gmult(a, gf_inv(a)) == 1 para todo $a \in [1, 255]$, definiendo $0^{-1} = 0$.

In [ ]:
# Escriba aquí su código y markdown

### **Actividad 4**: Aplica la transformación afín (affine transformation) de AES sobre $GF(2)$ al resultado de la inversión:

$$s_i' = s_i \oplus s_{(i+4) \bmod 8} \oplus s_{(i+5) \bmod 8} \oplus s_{(i+6) \bmod 8} \oplus s_{(i+7) \bmod 8} \oplus c_i$$

donde $c = \texttt{0x63}$

¿Por qué AES utiliza tanto la inversión de campo en $GF(2^8)$ como la transformación afín a nivel de bits, en lugar de utilizar únicamente la inversión algebraica?
(*Hint:* Investigar ataques algebraicos y el grado del polinomio de interpolación).

In [ ]:
# Escriba aquí su código y markdown

### Fin de la Tarea!!!